apiVersion: v1
kind: Pod
metadata:
  name: mynginxtestpod
  labels:
    name: mynginxtestpod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
