apiVersion: v1
kind: Pod
metadata:
  name: redispod
  labels:
    app: redispod
    name: test
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "50Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
