apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
      name: TestReplicationController
      app: nginx
spec:
  replicas: 3
  selector:
    name: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        #   - containerPort: 80
