apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myreplicaset
    labels:
      app: myapp
spec:
  template:
      metadata:
        name: myapp-pod
        labels:
          type: frontend
      spec:
        containers:
            - name: nginx
              image: nginx
  selector:
    matchLabels:
        type: frontend
  replicas: 3
      