apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rcset
  labels:
    name: myrcset
spec:
  template:
    metadata:
      name: myapp-2
      labels:
        name: myrcset
    spec:
      containers:
      - name: myapp
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: myrcset
