apiVersion: v1
kind: Service
metadata:
  name: mytestservice
spec:
  selector:
    name: mynginxtestpod
  ports:
  - port: 80
    name: myport
    targetPort: 80
    nodePort: 30012
  # - port: 443
  #   targetPort: 443
  #   nodePort: 30009
  type: NodePort
